// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://spjidbbdpwgsqxryliuy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNwamlkYmJkcHdnc3F4cnlsaXV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMTYzNzAsImV4cCI6MjA2NTg5MjM3MH0.wmo2C7EJNNERysNhup187R7vg9CYBaMNfAMGJ8I-qYQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);